version: '3.3'

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend
    # El puerto ya no es público, Caddy se conecta internamente por 'backend:8080'
    expose:
      - "8080"
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/uploads:/app/uploads
    restart: always
    environment:
      - PORT=8080
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=boston_club_secret_production_key_2026
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=mybostonclub@gmail.com
      - SMTP_PASS=wdnwarczeomsxhfs
      - MP_PUBLIC_KEY=APP_USR-fbaff93c-8312-4f79-9fc3-99af512023f4
      - MP_ACCESS_TOKEN=APP_USR-4294173646691405-042112-5bdeca0eaa1a4e5610e8828877e165b4-305616995

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://mybostonclub.com/api
    # El puerto ya no es público, Caddy se conecta internamente por 'frontend:3000'
    expose:
      - "3000"
    restart: always
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
