version: '3.3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: bostonclub
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./backend/uploads:/srv/uploads
    depends_on:
      - backend
      - frontend

  backend:
    build: 
      context: ./backend
    # El puerto ya no es público, Caddy se conecta internamente por 'backend:8080'
    expose:
      - "8080"
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/uploads:/app/uploads
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-postgres}@db:5432/bostonclub?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MP_PUBLIC_KEY=${MP_PUBLIC_KEY}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://mybostonclub.com/api
    # El puerto ya no es público, Caddy se conecta internamente por 'frontend:3000'
    expose:
      - "3000"
    restart: always
    depends_on:
      - backend

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
